Update events-and-binds.md
macroquest/docs pull request #52
Opened 2023-12-03 17:51 UTC by Zoh63392187

Invalid function -> end statement missing

2023-12-03 17:56 UTC, brainiac commented
This isn’t correct, only the first line is conditional

2023-12-03 18:52 UTC, Zoh63392187 commented
I guess my wording is not correct (Stupid Dane)

2023-12-04 20:25 UTC, brainiac requested changes

2023-12-04 20:25 UTC, brainiac commented on lua/events-and-binds.md
> +            str = str .. args[i]
this shouldn't be part of the condition. the condition was to add a space between arguments after the first.

2023-12-04 21:29 UTC, Zoh63392187 reviewed
All good

2023-12-08 21:18 UTC, merged