Standardization of formatting on Plugin pages.
macroquest/docs pull request #64
Opened 2024-08-02 21:35 UTC by yb-f

Removed plugins that no longer existed and attempted to standardize formatting across plugin pages to make a more readable and pleasurable experience.

Not all of the pages for plugins have been standardized yet, but it is a start.

2024-08-02 21:49 UTC, brainiac commented on plugins/community-plugins/mq2aapurchase.md
> +`/aapurchase help` -- List commands, aka this<br>
I would look at using the definition list format like we use for datatypes/tlos, or using a list. Using html blocks like this is an indicator that you're going against the grain.

2024-08-02 21:50 UTC, brainiac commented on plugins/community-plugins/mq2advpath.md
> +| [_bool_](../../reference/data-types/datatype-bool.md) | **Paused**       | Paused |
Look at how we're linking in the datatype pages with reference links to keep this easier to maintain.

2024-08-02 21:50 UTC, brainiac requested changes
Left two comments but they apply to the whole thing.

2024-08-02 21:53 UTC, yb-f commented
Will work on doing that tomorrow. Thanks for the input!

2024-08-12 04:35 UTC, merged

2024-08-12 04:35 UTC, brainiac commented
close enough.